"""Large product seed dataset for SI-ISPO marketplace + traceability demo."""
from typing import Dict, List, Any


def build_products_seed(plot_ids: Dict[str, str]) -> List[Dict[str, Any]]:
    """Return a list of product seed dicts following hulu→hilir chain.

    Each product references parents by *kode* (resolved by caller after insert).
    The caller is responsible for substituting kode→id in parent_ids/plot_id.
    """
    cert = lambda n: f"ISPO/CERT/2024/{n:04d}"

    return [
        # ─────────────── HULU (TBS) — 8 batches from various plots ───────────────
        dict(kode="TBS-RIA-001", nama="TBS Riau A1 — Panen Jan 2025 (Minggu 1)", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="PT Sawit Nusantara", jumlah=850, satuan="ton", batch_date="2025-01-08",
             plot="Kebun Inti Riau A1", ispo_certified=True, sertifikat_ispo=cert(1), siap_jual="Habis", halal_certified=True,
             deskripsi="TBS varietas Tenera, hasil panen kebun inti tersertifikasi ISPO. Free from deforestasi & lahan gambut.",
             spesifikasi="Kadar minyak: 22-24% | Berat tandan: 18-25 kg | OER: 22% | Kematangan: optimal"),
        dict(kode="TBS-RIA-002", nama="TBS Riau A1 — Panen Jan 2025 (Minggu 3)", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="PT Sawit Nusantara", jumlah=910, satuan="ton", batch_date="2025-01-22",
             plot="Kebun Inti Riau A1", ispo_certified=True, sertifikat_ispo=cert(1), siap_jual="Habis"),
        dict(kode="TBS-KBR-001", nama="TBS Kalbar C3 — Panen Feb 2025", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="PT Borneo Sawit Lestari", jumlah=1450, satuan="ton", batch_date="2025-02-10",
             plot="Kebun Kalbar C3", ispo_certified=True, sertifikat_ispo=cert(8), siap_jual="Habis"),
        dict(kode="TBS-KBR-002", nama="TBS Kalbar C3 — Panen Mar 2025", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="PT Borneo Sawit Lestari", jumlah=1280, satuan="ton", batch_date="2025-03-05",
             plot="Kebun Kalbar C3", ispo_certified=True, sertifikat_ispo=cert(8), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=2_800_000, minimum_order=50, lokasi_gudang="Pelabuhan Pontianak, Kalbar",
             deskripsi="TBS segar siap olah, panen 24 jam terakhir, dari kebun ISPO bersertifikat.",
             spesifikasi="OER: 23% | Free: bunch >25kg | Kadar air: <16%"),
        dict(kode="TBS-JBI-001", nama="TBS Jambi E5 — Panen Jan 2025", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="PT Industri Sawit Makmur", jumlah=620, satuan="ton", batch_date="2025-01-20",
             plot="Kebun Jambi E5", ispo_certified=True, sertifikat_ispo=cert(15), siap_jual="Habis"),
        dict(kode="TBS-JBI-002", nama="TBS Jambi E5 — Panen Feb 2025", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="PT Industri Sawit Makmur", jumlah=735, satuan="ton", batch_date="2025-02-18",
             plot="Kebun Jambi E5", ispo_certified=True, sertifikat_ispo=cert(15), siap_jual="Habis"),
        dict(kode="TBS-SMU-001", nama="TBS Sumut B2 — Panen Plasma Feb 2025", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="Kelompok Tani Makmur", jumlah=380, satuan="ton", batch_date="2025-02-14",
             plot="Kebun Plasma Sumut B2", ispo_certified=False, siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=2_650_000, minimum_order=20, lokasi_gudang="Labuhanbatu, Sumut",
             deskripsi="TBS pekebun plasma binaan, dalam proses audit ISPO. Kualitas baik, panen rutin.",
             spesifikasi="OER: 21% | Varietas: Tenera | Panen: rotasi 7 hari"),
        dict(kode="TBS-ACE-001", nama="TBS Aceh D4 — Panen Pekebun Mandiri", kategori="Hulu", jenis="Tandan Buah Segar (TBS)",
             produsen="Koperasi Tani Aceh", jumlah=180, satuan="ton", batch_date="2025-03-12",
             plot="Kebun Aceh D4", ispo_certified=False, siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=2_500_000, minimum_order=10, lokasi_gudang="Nagan Raya, Aceh",
             deskripsi="TBS pekebun mandiri Aceh, sedang persiapan ISPO. Diversifikasi varietas.",
             spesifikasi="OER: 20% | Asal: kebun rakyat"),

        # ─────────────── RAFINASI: CPO — multiple PKS ───────────────
        dict(kode="CPO-RIA-001", nama="CPO Riau Batch Jan 2025", kategori="Rafinasi", jenis="CPO (Crude Palm Oil)",
             produsen="PKS Pelalawan", jumlah=185, satuan="ton", batch_date="2025-01-18",
             parents=["TBS-RIA-001"], ispo_certified=True, sertifikat_ispo=cert(1), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=12_800_000, minimum_order=25, lokasi_gudang="Tangki Dumai, Riau",
             deskripsi="CPO hasil ekstraksi dari TBS kebun inti Riau A1. ISPO + ISCC tersertifikasi.",
             spesifikasi="FFA: <3.5% | DOBI: 2.5 min | Moisture: <0.25% | M&I: <0.5%"),
        dict(kode="CPO-RIA-002", nama="CPO Riau Batch Feb 2025", kategori="Rafinasi", jenis="CPO (Crude Palm Oil)",
             produsen="PKS Pelalawan", jumlah=210, satuan="ton", batch_date="2025-02-08",
             parents=["TBS-RIA-002"], ispo_certified=True, sertifikat_ispo=cert(1), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=12_950_000, minimum_order=25, lokasi_gudang="Tangki Dumai, Riau"),
        dict(kode="CPO-KBR-001", nama="CPO Kalbar Batch Feb 2025", kategori="Rafinasi", jenis="CPO (Crude Palm Oil)",
             produsen="PKS Ketapang", jumlah=310, satuan="ton", batch_date="2025-02-12",
             parents=["TBS-KBR-001"], ispo_certified=True, sertifikat_ispo=cert(8), siap_jual="Habis"),
        dict(kode="CPO-KBR-002", nama="CPO Kalbar Batch Mar 2025", kategori="Rafinasi", jenis="CPO (Crude Palm Oil)",
             produsen="PKS Ketapang", jumlah=290, satuan="ton", batch_date="2025-03-08",
             parents=["TBS-KBR-002"], ispo_certified=True, sertifikat_ispo=cert(8), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=12_700_000, minimum_order=50, lokasi_gudang="Pelabuhan Pontianak"),
        dict(kode="CPO-JBI-001", nama="CPO Jambi Batch Jan 2025", kategori="Rafinasi", jenis="CPO (Crude Palm Oil)",
             produsen="PKS Muaro Jambi", jumlah=135, satuan="ton", batch_date="2025-01-22",
             parents=["TBS-JBI-001"], ispo_certified=True, sertifikat_ispo=cert(15), siap_jual="Habis"),
        dict(kode="CPO-JBI-002", nama="CPO Jambi Batch Feb 2025", kategori="Rafinasi", jenis="CPO (Crude Palm Oil)",
             produsen="PKS Muaro Jambi", jumlah=158, satuan="ton", batch_date="2025-02-20",
             parents=["TBS-JBI-002"], ispo_certified=True, sertifikat_ispo=cert(15), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=12_850_000, minimum_order=25, lokasi_gudang="Tangki Jambi"),
        dict(kode="CPO-SMU-001", nama="CPO Sumut Batch Feb 2025 (Plasma)", kategori="Rafinasi", jenis="CPO (Crude Palm Oil)",
             produsen="PKS Labuhanbatu", jumlah=82, satuan="ton", batch_date="2025-02-16",
             parents=["TBS-SMU-001"], ispo_certified=False, siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=12_400_000, minimum_order=20, lokasi_gudang="PKS Labuhanbatu, Sumut"),

        # ─────────────── PKO + Palm Kernel Cake ───────────────
        dict(kode="PKO-RIA-001", nama="PKO Riau Batch Jan 2025", kategori="Rafinasi", jenis="PKO (Palm Kernel Oil)",
             produsen="PKS Pelalawan", jumlah=20, satuan="ton", batch_date="2025-01-18",
             parents=["TBS-RIA-001"], ispo_certified=True, sertifikat_ispo=cert(1), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=18_200_000, minimum_order=5, lokasi_gudang="Tangki Dumai"),
        dict(kode="PKO-KBR-001", nama="PKO Kalbar Batch Feb 2025", kategori="Rafinasi", jenis="PKO (Palm Kernel Oil)",
             produsen="PKS Ketapang", jumlah=35, satuan="ton", batch_date="2025-02-15",
             parents=["TBS-KBR-001"], ispo_certified=True, sertifikat_ispo=cert(8), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=18_500_000, minimum_order=10, lokasi_gudang="Pontianak"),
        dict(kode="PKC-001", nama="Palm Kernel Cake (Bungkil Inti Sawit)", kategori="Rafinasi", jenis="Palm Kernel Cake",
             produsen="PKS Pelalawan", jumlah=180, satuan="ton", batch_date="2025-01-20",
             parents=["TBS-RIA-001"], ispo_certified=True, sertifikat_ispo=cert(1), siap_jual="Siap Jual",
             tersedia_marketplace=True, harga=2_400_000, minimum_order=20, lokasi_gudang="Pelalawan",
             deskripsi="Bungkil hasil ekstraksi PKO. Bahan pakan ternak protein tinggi.",
             spesifikasi="Protein: 16-18% | Lemak: 5-7% | Serat: 14-16%"),

        # ─────────────── RBD / Olein / Stearin ───────────────
        dict(kode="RBD-001", nama="RBD Palm Oil Batch Feb 2025", kategori="Rafinasi", jenis="RBD Palm Oil",
             produsen="PT Refinery Sumut", jumlah=420, satuan="ton", batch_date="2025-02-15",
             parents=["CPO-RIA-001", "CPO-KBR-001"], ispo_certified=True, sertifikat_ispo=cert(22),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=13_500_000, minimum_order=25,
             lokasi_gudang="Belawan, Sumut",
             deskripsi="RBD Palm Oil (Refined, Bleached, Deodorized) feedstock untuk fraksinasi.",
             spesifikasi="FFA: <0.1% | Color: 3R/30Y max | M&I: <0.1%"),
        dict(kode="RBD-002", nama="RBD Palm Oil Batch Mar 2025", kategori="Rafinasi", jenis="RBD Palm Oil",
             produsen="PT Refinery Sumut", jumlah=380, satuan="ton", batch_date="2025-03-10",
             parents=["CPO-KBR-002", "CPO-JBI-002"], ispo_certified=True, sertifikat_ispo=cert(22),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=13_600_000, minimum_order=25,
             lokasi_gudang="Belawan, Sumut"),
        dict(kode="OLN-001", nama="Palm Olein RBD Batch Feb 2025", kategori="Rafinasi", jenis="Palm Olein",
             produsen="PT Refinery Sumut", jumlah=290, satuan="ton", batch_date="2025-02-18",
             parents=["RBD-001"], ispo_certified=True, sertifikat_ispo=cert(22),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=14_200_000, minimum_order=25,
             lokasi_gudang="Belawan, Sumut",
             deskripsi="Fraksi cair RBD Palm Oil, IV 56 min. Untuk minyak goreng & food industry.",
             spesifikasi="Iodine Value: 56 min | Cloud Point: 8-10°C | FFA: <0.1%"),
        dict(kode="OLN-002", nama="Palm Olein RBD Batch Mar 2025", kategori="Rafinasi", jenis="Palm Olein",
             produsen="PT Refinery Sumut", jumlah=260, satuan="ton", batch_date="2025-03-12",
             parents=["RBD-002"], ispo_certified=True, sertifikat_ispo=cert(22),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=14_400_000, minimum_order=25,
             lokasi_gudang="Belawan, Sumut"),
        dict(kode="STR-001", nama="Palm Stearin Batch Feb 2025", kategori="Rafinasi", jenis="Palm Stearin",
             produsen="PT Refinery Sumut", jumlah=120, satuan="ton", batch_date="2025-02-18",
             parents=["RBD-001"], ispo_certified=True, sertifikat_ispo=cert(22),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=12_900_000, minimum_order=20,
             lokasi_gudang="Belawan, Sumut",
             deskripsi="Fraksi padat dari RBD Palm Oil. Untuk margarin, shortening, soap base.",
             spesifikasi="Iodine Value: 48 max | SMP: 50-54°C | FFA: <0.1%"),
        dict(kode="STR-002", nama="Palm Stearin Batch Mar 2025", kategori="Rafinasi", jenis="Palm Stearin",
             produsen="PT Refinery Sumut", jumlah=105, satuan="ton", batch_date="2025-03-12",
             parents=["RBD-002"], ispo_certified=True, sertifikat_ispo=cert(22),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=12_950_000, minimum_order=20,
             lokasi_gudang="Belawan, Sumut"),

        # ─────────────── PANGAN: Minyak Goreng (3 brand, multiple SKU) ───────────────
        dict(kode="MG-001", nama="SawitMurni Minyak Goreng 1L (Botol PET)", kategori="Pangan", jenis="Minyak Goreng Sawit",
             produsen="PT Pangan Sawit", jumlah=80000, satuan="botol", batch_date="2025-02-20",
             parents=["OLN-001"], ispo_certified=True, sertifikat_ispo=cert(22), halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=18_500, minimum_order=1000,
             lokasi_gudang="Gudang Medan, Sumut",
             deskripsi="Minyak goreng sawit kemasan botol PET 1L. Jernih, tidak berbau, kaya vitamin A.",
             spesifikasi="Volume: 1L | FFA: <0.1% | Vitamin A: 45 IU/g | Halal MUI | BPOM RI MD"),
        dict(kode="MG-002", nama="SawitMurni Minyak Goreng 2L (Pouch)", kategori="Pangan", jenis="Minyak Goreng Sawit",
             produsen="PT Pangan Sawit", jumlah=45000, satuan="pouch", batch_date="2025-02-22",
             parents=["OLN-001"], ispo_certified=True, sertifikat_ispo=cert(22), halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=35_000, minimum_order=500,
             lokasi_gudang="Gudang Medan, Sumut"),
        dict(kode="MG-003", nama="SawitMurni Minyak Goreng 5L (Jerigen)", kategori="Pangan", jenis="Minyak Goreng Sawit",
             produsen="PT Pangan Sawit", jumlah=18000, satuan="jerigen", batch_date="2025-02-24",
             parents=["OLN-001"], ispo_certified=True, sertifikat_ispo=cert(22), halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=85_000, minimum_order=100,
             lokasi_gudang="Gudang Medan, Sumut"),
        dict(kode="MG-004", nama="HijauEco Minyak Goreng 1L (refill)", kategori="Pangan", jenis="Minyak Goreng Sawit",
             produsen="PT Hijau Pangan", jumlah=62000, satuan="botol", batch_date="2025-03-15",
             parents=["OLN-002"], ispo_certified=True, sertifikat_ispo=cert(22), halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=17_900, minimum_order=1000,
             lokasi_gudang="Jakarta",
             deskripsi="Minyak goreng dengan kemasan refill ramah lingkungan, harga kompetitif.",
             spesifikasi="Volume: 1L | Vitamin A: 45 IU | Halal MUI"),
        dict(kode="MG-005", nama="BoengaSawit Minyak Goreng 1L Premium", kategori="Pangan", jenis="Minyak Goreng Sawit",
             produsen="PT Premium Foods", jumlah=22000, satuan="botol", batch_date="2025-03-18",
             parents=["OLN-002"], ispo_certified=True, sertifikat_ispo=cert(22), halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=24_500, minimum_order=500,
             lokasi_gudang="Surabaya",
             deskripsi="Minyak goreng premium, double filtration, untuk restoran & food service.",
             spesifikasi="Volume: 1L | FFA: <0.05% | Premium grade | Halal MUI"),

        # ─────────────── PANGAN: Margarin & Specialty Fats ───────────────
        dict(kode="MARG-001", nama="ButterPalm Margarin Premium 250g", kategori="Pangan", jenis="Margarin",
             produsen="PT Pangan Sawit", jumlah=50000, satuan="pcs", batch_date="2025-02-22",
             parents=["STR-001", "OLN-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=12_000, minimum_order=500,
             lokasi_gudang="Surabaya"),
        dict(kode="MARG-002", nama="ButterPalm Margarin Industrial 5kg", kategori="Pangan", jenis="Margarin",
             produsen="PT Pangan Sawit", jumlah=12000, satuan="pcs", batch_date="2025-03-10",
             parents=["STR-002", "OLN-002"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=180_000, minimum_order=100,
             lokasi_gudang="Surabaya",
             deskripsi="Margarin ukuran industri untuk bakery & pastry.",
             spesifikasi="Berat: 5kg | SFC@10°C: 60% | Halal MUI"),
        dict(kode="SHRT-001", nama="GoldenShort Shortening 15kg", kategori="Pangan", jenis="Shortening",
             produsen="PT Premium Foods", jumlah=8000, satuan="pcs", batch_date="2025-03-05",
             parents=["STR-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=420_000, minimum_order=20,
             lokasi_gudang="Surabaya",
             deskripsi="Shortening 100% palm-based, trans fat free, untuk bakery industri.",
             spesifikasi="Berat: 15kg | Trans fat: 0 | SMP: 42°C"),
        dict(kode="SF-001", nama="CocoaButter Substitute (CBS) 25kg", kategori="Pangan", jenis="Lemak Khusus (Specialty Fats)",
             produsen="PT Pangan Sawit", jumlah=8000, satuan="kg", batch_date="2025-02-25",
             parents=["STR-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=85_000, minimum_order=200,
             lokasi_gudang="Jakarta"),
        dict(kode="SF-002", nama="Frying Fat HOMG-Stable", kategori="Pangan", jenis="Lemak Khusus (Specialty Fats)",
             produsen="PT Premium Foods", jumlah=4500, satuan="kg", batch_date="2025-03-18",
             parents=["STR-002"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=72_000, minimum_order=100,
             lokasi_gudang="Jakarta",
             deskripsi="Lemak khusus tahan oksidasi untuk industri snack & deep frying.",
             spesifikasi="Smoke point: 230°C | Oxidative stability: 25 hr"),
        dict(kode="PKN-001", nama="Pakan Ternak Sapi Palm-Based 25kg", kategori="Pangan", jenis="Pakan Ternak Berbasis Sawit",
             produsen="PT Pakan Nusantara", jumlah=15000, satuan="karung", batch_date="2025-02-26",
             parents=["PKC-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=185_000, minimum_order=50,
             lokasi_gudang="Pekanbaru, Riau"),
        dict(kode="PKN-002", nama="Pakan Unggas Palm-Mix 50kg", kategori="Pangan", jenis="Pakan Ternak Berbasis Sawit",
             produsen="PT Pakan Nusantara", jumlah=9500, satuan="karung", batch_date="2025-03-08",
             parents=["PKC-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=325_000, minimum_order=20,
             lokasi_gudang="Pekanbaru, Riau"),

        # ─────────────── OLEOKIMIA: Fatty Acid, Glycerol, ME ───────────────
        dict(kode="FA-001", nama="Asam Lemak C12-C18 (Splitting PKO)", kategori="Oleokimia", jenis="Asam Lemak (Fatty Acids)",
             produsen="PT Oleo Indonesia", jumlah=180, satuan="ton", batch_date="2025-03-01",
             parents=["PKO-RIA-001"], ispo_certified=True, sertifikat_ispo=cert(33),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=14_500_000, minimum_order=20,
             lokasi_gudang="Dumai, Riau"),
        dict(kode="FA-002", nama="Asam Lemak Stearat Murni 99%", kategori="Oleokimia", jenis="Asam Lemak (Fatty Acids)",
             produsen="PT Oleo Indonesia", jumlah=85, satuan="ton", batch_date="2025-03-15",
             parents=["PKO-KBR-001"], ispo_certified=True, sertifikat_ispo=cert(33),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=18_200_000, minimum_order=10,
             lokasi_gudang="Cilegon, Banten",
             deskripsi="Asam stearat murni 99% untuk industri rubber, lilin, kosmetik premium.",
             spesifikasi="Purity: 99% | Iodine: <0.5 | Acid value: 207"),
        dict(kode="GL-001", nama="Gliserol Industri 80%", kategori="Oleokimia", jenis="Gliserol / Gliserin",
             produsen="PT Oleo Indonesia", jumlah=45, satuan="ton", batch_date="2025-03-01",
             parents=["PKO-RIA-001"], ispo_certified=True, sertifikat_ispo=cert(33),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=11_000_000, minimum_order=10,
             lokasi_gudang="Dumai, Riau"),
        dict(kode="GL-002", nama="Gliserol Refined USP/Pharmaceutical Grade", kategori="Oleokimia", jenis="Gliserol / Gliserin",
             produsen="PT Oleo Indonesia", jumlah=22, satuan="ton", batch_date="2025-03-12",
             parents=["PKO-KBR-001"], ispo_certified=True, sertifikat_ispo=cert(33), halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=24_500_000, minimum_order=2,
             lokasi_gudang="Cilegon, Banten",
             deskripsi="Gliserol food/pharma grade. Untuk farmasi, kosmetik, makanan.",
             spesifikasi="Purity: 99.5% | USP/EP compliant | Color: <10 APHA"),
        dict(kode="ME-001", nama="Fatty Acid Methyl Ester (FAME)", kategori="Oleokimia", jenis="Metil Ester",
             produsen="PT Oleo Indonesia", jumlah=220, satuan="ton", batch_date="2025-03-03",
             parents=["CPO-JBI-001"], ispo_certified=True, sertifikat_ispo=cert(33),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=13_800_000, minimum_order=25,
             lokasi_gudang="Cilegon, Banten"),
        dict(kode="ME-002", nama="Methyl Laurate (C12)", kategori="Oleokimia", jenis="Metil Ester",
             produsen="PT Oleo Indonesia", jumlah=48, satuan="ton", batch_date="2025-03-20",
             parents=["PKO-RIA-001"], ispo_certified=True, sertifikat_ispo=cert(33),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=22_000_000, minimum_order=5,
             lokasi_gudang="Cilegon, Banten",
             deskripsi="Methyl ester rantai C12, untuk surfaktan & deterjen premium.",
             spesifikasi="Purity: 98% min | Iodine: <1.0"),

        # ─────────────── OLEOKIMIA: Sabun, Detergen, Kosmetik ───────────────
        dict(kode="SB-001", nama="LuxiSoap Sabun Mandi Batang 80g", kategori="Oleokimia", jenis="Sabun & Deterjen Berbasis Sawit",
             produsen="PT Sabun Nusantara", jumlah=120000, satuan="pcs", batch_date="2025-03-05",
             parents=["FA-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=4_500, minimum_order=2000,
             lokasi_gudang="Bekasi, Jawa Barat"),
        dict(kode="SB-002", nama="LuxiSoap Sabun Cuci Batang 200g", kategori="Oleokimia", jenis="Sabun & Deterjen Berbasis Sawit",
             produsen="PT Sabun Nusantara", jumlah=85000, satuan="pcs", batch_date="2025-03-08",
             parents=["FA-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=3_200, minimum_order=2000,
             lokasi_gudang="Bekasi, Jawa Barat"),
        dict(kode="DET-001", nama="EcoWash Deterjen Cair 1L (refill)", kategori="Oleokimia", jenis="Sabun & Deterjen Berbasis Sawit",
             produsen="PT Sabun Nusantara", jumlah=42000, satuan="pcs", batch_date="2025-03-15",
             parents=["FA-002", "ME-002"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=18_500, minimum_order=500,
             lokasi_gudang="Bekasi, Jawa Barat",
             deskripsi="Deterjen cair konsentrat berbasis surfaktan sawit. Biodegradable.",
             spesifikasi="Volume: 1L | Biodegradability: 95% | pH: 7-8"),
        dict(kode="DET-002", nama="EcoWash Sabun Cuci Piring 800ml", kategori="Oleokimia", jenis="Sabun & Deterjen Berbasis Sawit",
             produsen="PT Sabun Nusantara", jumlah=58000, satuan="pcs", batch_date="2025-03-18",
             parents=["ME-002"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=9_800, minimum_order=1000,
             lokasi_gudang="Bekasi"),
        dict(kode="KS-001", nama="GlowLotion Body Lotion 200ml", kategori="Oleokimia", jenis="Kosmetik & Perawatan Tubuh",
             produsen="PT Beauty Sawit", jumlah=25000, satuan="pcs", batch_date="2025-03-08",
             parents=["FA-001", "GL-001"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=28_000, minimum_order=500,
             lokasi_gudang="Jakarta"),
        dict(kode="KS-002", nama="GlowLotion Hand Cream 100ml", kategori="Oleokimia", jenis="Kosmetik & Perawatan Tubuh",
             produsen="PT Beauty Sawit", jumlah=42000, satuan="pcs", batch_date="2025-03-12",
             parents=["GL-002"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=22_000, minimum_order=500,
             lokasi_gudang="Jakarta",
             deskripsi="Hand cream pelembab dengan gliserin pharma grade.",
             spesifikasi="Volume: 100ml | pH: 5.5 | Halal MUI | Free paraben"),
        dict(kode="KS-003", nama="PalmShampoo Premium 250ml", kategori="Oleokimia", jenis="Kosmetik & Perawatan Tubuh",
             produsen="PT Beauty Sawit", jumlah=38000, satuan="pcs", batch_date="2025-03-15",
             parents=["ME-002", "GL-002"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=32_000, minimum_order=500,
             lokasi_gudang="Jakarta"),
        dict(kode="KS-004", nama="PalmBeauty Lipstick (set 6 warna)", kategori="Oleokimia", jenis="Kosmetik & Perawatan Tubuh",
             produsen="PT Beauty Sawit", jumlah=8500, satuan="set", batch_date="2025-03-22",
             parents=["FA-002", "STR-002"], ispo_certified=True, halal_certified=True,
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=185_000, minimum_order=50,
             lokasi_gudang="Jakarta",
             deskripsi="Lipstick set 6 warna dengan palm stearin + asam stearat. Vegan-friendly.",
             spesifikasi="Set: 6 pcs | Wax base: palm stearin | Halal MUI"),

        # ─────────────── BIOENERGI: Biodiesel B20/B30/B40, Biomassa, Biogas ───────────────
        dict(kode="BD-001", nama="Biodiesel B30 (FAME Blend)", kategori="Bioenergi", jenis="Biodiesel (Bahan Bakar Nabati)",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=210, satuan="ton", batch_date="2025-03-10",
             parents=["ME-001", "OLN-001"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=12_500_000, minimum_order=50,
             lokasi_gudang="Terminal Tj. Priok, Jakarta"),
        dict(kode="BD-002", nama="Biodiesel B40 (FAME Blend Pre-Mix)", kategori="Bioenergi", jenis="Biodiesel (Bahan Bakar Nabati)",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=180, satuan="ton", batch_date="2025-03-20",
             parents=["ME-001", "OLN-002"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=12_800_000, minimum_order=50,
             lokasi_gudang="Terminal Tj. Priok, Jakarta",
             deskripsi="Biodiesel campuran 40% FAME — sesuai roadmap pemerintah B40 (2025+).",
             spesifikasi="Cetane: 51 min | FAME content: 40% | EN 14214"),
        dict(kode="BD-003", nama="Biodiesel B100 Pure FAME (Export Grade)", kategori="Bioenergi", jenis="Biodiesel (Bahan Bakar Nabati)",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=95, satuan="ton", batch_date="2025-03-25",
             parents=["ME-001"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=14_200_000, minimum_order=25,
             lokasi_gudang="Cilegon, Banten",
             deskripsi="FAME 100% murni untuk pasar ekspor EU (RED II compliant).",
             spesifikasi="FAME: 100% | EN 14214 + RED II | GHG saving: 75%"),
        dict(kode="BM-001", nama="Palm Kernel Shell (PKS) — Biomass Fuel", kategori="Bioenergi", jenis="Biomassa",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=350, satuan="ton", batch_date="2025-03-11",
             parents=["TBS-KBR-001"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=850_000, minimum_order=100,
             lokasi_gudang="Pelabuhan Pontianak, Kalbar"),
        dict(kode="BM-002", nama="Empty Fruit Bunch (EFB) Pellets", kategori="Bioenergi", jenis="Biomassa",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=480, satuan="ton", batch_date="2025-03-18",
             parents=["TBS-KBR-002"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=720_000, minimum_order=100,
             lokasi_gudang="Pelabuhan Pontianak",
             deskripsi="Tandan kosong (EFB) pellets — biomass fuel untuk co-firing PLTU.",
             spesifikasi="Calorific value: 3800 kcal/kg | Moisture: <12% | Pellet diameter: 8mm"),
        dict(kode="BM-003", nama="Mesocarp Fiber Biomass", kategori="Bioenergi", jenis="Biomassa",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=220, satuan="ton", batch_date="2025-03-22",
             parents=["TBS-RIA-002"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=650_000, minimum_order=50,
             lokasi_gudang="Dumai, Riau"),
        dict(kode="BG-001", nama="Biogas POME Plant Ketapang", kategori="Bioenergi", jenis="Biogas (POME)",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=85000, satuan="m³", batch_date="2025-03-12",
             parents=["CPO-KBR-001"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=4_500, minimum_order=5000,
             lokasi_gudang="Pabrik Ketapang, Kalbar"),
        dict(kode="BG-002", nama="Biogas POME Plant Jambi", kategori="Bioenergi", jenis="Biogas (POME)",
             produsen="PT Bioenergi Sawit Indonesia", jumlah=62000, satuan="m³", batch_date="2025-03-20",
             parents=["CPO-JBI-002"], ispo_certified=True, sertifikat_ispo=cert(45),
             siap_jual="Siap Jual", tersedia_marketplace=True, harga=4_400, minimum_order=5000,
             lokasi_gudang="Pabrik Jambi",
             deskripsi="Biogas hasil pengolahan POME Pabrik Jambi. Untuk PLTBg captive.",
             spesifikasi="CH4: 60% | H2S: <300 ppm | Daya: 800 kW listrik"),
    ]
